--- 
layout: post
status: publish
meta: 
  blogger_blog: brunosan.blogspot.com
  blogger_author: "Bruno S\xC3\xA1nchez-Andrade Nu\xC3\xB1o"
  blogger_84811d3284c06b3cad7acdc4a1b30d1c_permalink: "4402645067300302173"
published: true
type: post
tags: 
- Science
title: "Nuestros juguetes en \xC3\xB3rbita"
---
No sé muy bien como acabé encontrando esta capa de Google Earth:<br /><a href="http://adn.agi.com/SatelliteDatabase/SatelliteDatabase.kmz">Tracking Satellites</a><br /><br />Se trata de la posición, en tiempo casi real, de todos los satélites que orbitan la Tierra. Bueno, de aquellos que l<a href="http://www.stratcom.mil/">os americanos</a> vigilan. Y, obviamente, faltan los militares, y seguro que mucho que ya no funcionen. El kmz es de <a href="http://www.agi.com/">esta empresa</a>, y <a href="http://earth.google.es/">Google earth</a>, bueno, creo que todos lo conocemos.<br /><br /><a href="http://nasonurb.files.wordpress.com/2008/09/picture12.jpg"><img src="http://nasonurb.files.wordpress.com/2008/09/picture12.jpg?w=300" border="0" /></a><br /><br />Esta capa ayuda a hacerse uno a la idea de la cantidad de satélites que están ahí fuera. De lo dependientes de ellos que podemos ser, y de la cantidad de basura que estamos generando, que ya traspasa la frontera del espacio.<br /><br />Los hay de comunicaciones, científicos, de gobiernos, de empresas privadas, de hacer fotos, ... de todo los colores y tamaños. <br /><br />Los de órbita baja se mueven muy rápido (si no se caerían), pero duran tambien menos, porque se van frenando con la fricción de la ténue atmósfera. Si pinchas con el botón derecho a un satélites puedes pintar su órbita. Los que están bajos a unos 300 km dan la vuelta a la Tierra en 90 minutos. Por ejemplo la Estación Espacial Internacional.<br /><br />Cuanto más arriba están más lento van, de hecho, a una altura de unos 35700 Km, tardan 24 horas, osea la misma velocidad con la que gira la Tierra. Lo que pasa entonces es que están siempre sobre el mismo punto de la Tierra, son los geoestacionarios, y hay algo así como <a href="http://en.wikipedia.org/wiki/Geosynchronous_satellite">300</a>.<br /><br />Afortunadamente los satélites, aunque puedan ser grandes como autobuses, están tan lejos que no los vemos. Aunque si lo hiciéramos, creo que la gente sería más consciente de lo que es la <a href="http://es.wikipedia.org/wiki/Basura_espacial">"basura espacial".</a> Lo que sí que pasa a veces es que los paneles solares de los satélites se alinean de vez cuando de forma que reflejan la luz del sol hacia la Tierra. Cuando esto pasa se ve un punto brillante, que puede moverse rápido o estar quieto, dependiendo de la altura de la óribta del satélita, y puede durar más o menos, dependiendo de la velocidad de rotación del satélite.<br /><br />¿Qué pasaría si de repende todos los satélites se estropearan a la vez? ¿Que consecuencias tendría? No lo sé, pero muchas muchas. Y, ¿saben lo peor? es muy posible que ocurra en <a href="http://solarscience.msfc.nasa.gov/images/ssn_predict_l.gif">2011-2012</a>
